### ISSUE TITLE
site.logo is relative while page.image is absolute

### ISSUE THREAD

**Issue by boturnbow** [benbalter/jekyll-seo-tag#24]
Is it necessary to make page.image an absolute URL instead of relative? It would be much nicer to make it relative like site.logo. Thanks for a nice gem!

**Comment by pathawks** [comment]
If we are looking at the same code, it would appear that [`site.logo` is expected to be relative](https://github.com/benbalter/jekyll-seo-tag/blob/v0.1.4/lib/template.html#L111), while [`page.image` can be whatever](https://github.com/benbalter/jekyll-seo-tag/blob/v0.1.4/lib/template.html#L69).

It seems that `page.image` offers more flexibility. By not prepending the site URL, the URL can host the image on a third-party service like Flickr or S3.

Since Jekyll does not really have any standard way of dealing with images, I would vote to just leave it entirely up to the user and output the raw image URLs without prepending the site URL.

**Comment by pathawks** [comment]
I was going to lookup how **jekyll-feed** deals with this, but it does not include any thumbnails or logos in the site feed.

**Comment by boturnbow** [comment]
That's it - thanks for being much clearer than me. I agree that an absolute URL is more flexible than relative. But I think of a Jekyll site as being mostly self-contained or at least allowing that option. I can't remember another instance of an absolute url in a page's front matter. I expect to configure a host and baseurl in _config.yml, but not absolute elsewhere in a site. Maybe I'm imagining a "policy" where there is none?

**Comment by pathawks** [comment]
So, you'd like `page.image` to also have the site URL prepended to it, to match the behavior of `site.logo`? Do I understand?

**Comment by boturnbow** [comment]
Yes, I would like page.image to match the [URL construction of site.logo](https://github.com/benbalter/jekyll-seo-tag/blob/master/lib/template.html#L111) with the seo_url and a / prepended. What do you think?
